services:

  postgres:
    image: postgres:14-alpine
    container_name: and_project_db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      TZ: "Asia/Bangkok"
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  db:
